### ISSUE TITLE
聊天模板输入框显示不全

### ISSUE THREAD

**Issue by yimengshinian** [dingyong0214/ThorUI-uniapp#1]
iphonex -- 真机 , 聊天模板中的输入框显示不全

![微信图片_20190709094225](https://user-images.githubusercontent.com/46439489/60853270-e0304a80-a22d-11e9-90ff-088d033871d8.jpg)

**Comment by yinxiaorong** [comment]
这个我感觉你添加一个判断就好了，在苹果X机型下，添加一个padding-bottom

**Comment by dingyong0214** [comment]
不需要加判断，此问题已修复，感谢反馈
