### ISSUE TITLE
tui-button组件对微信form submit捕捉事件问题

### ISSUE THREAD

**Issue by catfishlty** [dingyong0214/ThorUI-uniapp#10]
使用`tui-button`组件不能触发`form`的`submit`事件
修改前，这种使用方式不能触发
```
<form @submit="handleSubmit">
    <tui-button formType="submit" type="primary">提交</tui-button>
</form>
```
修改后，这种方式可以正确捕获
```
<form @submit="handleSubmit">
    <button class="tui-btn tui-primary" hover-class="tui-primary-hover" formType="submit">提交</button>
</form>
```

**Comment by hxzAugustinus** [comment]
tui-button是组件， 会形成自己的作用域 ，你看渲染后的tui-button 下面有个 #shadow-root，所以像你这种场景需求别用组件。

**Comment by catfishlty** [comment]
> tui-button是组件， 会形成自己的作用域 ，你看渲染后的tui-button 下面有个 #shadow-root，所以像你这种场景需求别用组件。

确实是这样的情况，正因如此，导致了在这种场景下只能借助于原生组件配合css来达到UI效果的同时满足业务需求。
