### ISSUE TITLE
上传组件在安卓点击无反应

### ISSUE THREAD

**Issue by hxm-666** [dingyong0214/ThorUI-uniapp#101]
微信小程序嵌套的webview换成有上传功能的H5页面后，ios，微信开发工具，h5页面没问题，在安卓点击上传时没反应

**Comment by brotherzhoujie** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dingyong0214** [comment]
检查一下是否有层级覆盖的情况，这边排查webview嵌套H5在android可正常上传。
