### ISSUE TITLE
tuiButton 组件支付宝小程序使用编译出错

### ISSUE THREAD

**Issue by Jaden9527** [dingyong0214/ThorUI-uniapp#106]
// #ifndef MP-QQ
		behaviors: ['wx://form-field-button'],
		// #endif

测试发现支付宝小城打不开是 这句代码引起的，希望修复一下

**Comment by brotherzhoujie** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by brotherzhoujie** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
