### ISSUE TITLE
TuiGridItem 设置 prop "cell"时，提示Vue warn

### ISSUE THREAD

**Issue by zhuewizz** [dingyong0214/ThorUI-uniapp#11]
Vue warn]: Invalid prop: type check failed for prop "cell". Expected Number with value 5, got String with value "5".

found in

---> <TuiGridItem> at Users/zhuwei/HBuilderProjects/Start_Rfid/components/grid-item/grid-item.vue
       <VUniView>
         <TuiGrid> at Users/zhuwei/HBuilderProjects/Start_Rfid/components/grid/grid.vue
           <VUniView>... (1 recursive calls)
             <TuiCard> at Users/zhuwei/HBuilderProjects/Start_Rfid/components/card/card.vue
               <VUniView>
                 <Root>
                   <PageBody>
                     <Page>
                       <PagesHomeHome5>
                         <App>
                           <Root>

**Comment by dingyong0214** [comment]
Number类型传值需要加冒号



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhuewizz <notifications@github.com&gt;
发送时间: 2019年11月7日 19:20
收件人: dingyong0214/ThorUI-uniapp <ThorUI-uniapp@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dingyong0214/ThorUI-uniapp] TuiGridItem 设置 prop "cell"时，提示Vue warn (#11)




Vue warn]: Invalid prop: type check failed for prop "cell". Expected Number with value 5, got String with value "5".
 
found in
 
---&gt;  at Users/zhuwei/HBuilderProjects/Start_Rfid/components/grid-item/grid-item.vue
 
  at Users/zhuwei/HBuilderProjects/Start_Rfid/components/grid/grid.vue
 ... (1 recursive calls)
  at Users/zhuwei/HBuilderProjects/Start_Rfid/components/card/card.vue
