### ISSUE TITLE
tui-modal设置backgroundColor属性不生效

### ISSUE THREAD

**Issue by lyck40012** [dingyong0214/ThorUI-uniapp#110]
![image](https://github.com/dingyong0214/ThorUI-uniapp/assets/84356203/f54ffd41-621b-40d6-994e-e0d01d62b8f4)
![image](https://github.com/dingyong0214/ThorUI-uniapp/assets/84356203/6c56dd94-eaf8-4e79-a065-c166a77f25de)

**Comment by dingyong0214** [comment]
此属性在自定义内容下无效，自定义内容所有内容样式需自己去写
