### ISSUE TITLE
tui-modal 弹框 中添加 list，在小程序中无法滚动

### ISSUE THREAD

**Issue by KocoClass** [dingyong0214/ThorUI-uniapp#111]
tui-modal 弹框 中添加 list，在小程序中无法滚动，但是模拟器中可以用鼠标滚轮滚动

**Comment by brotherzhoujie** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dingyong0214** [comment]
内容套一个scroll-view
