### ISSUE TITLE
CheckBox组件是删了么？

### ISSUE THREAD

**Issue by Argun** [dingyong0214/ThorUI-uniapp#112]
找了半天没找到，是会员限定么？

![image](https://github.com/dingyong0214/ThorUI-uniapp/assets/1279340/292d56ed-bf4b-448d-a0da-892ec1531cb7)
![image](https://github.com/dingyong0214/ThorUI-uniapp/assets/1279340/56241796-e391-4650-bb0e-f57c01f4f8ae)
![image](https://github.com/dingyong0214/ThorUI-uniapp/assets/1279340/282594f5-965c-417c-af65-0f10d18b2c62)

**Comment by dingyong0214** [comment]
会员组件
