### ISSUE TITLE
使用swipe-action乱码问题

### ISSUE THREAD

**Issue by Give-me-sweets** [dingyong0214/ThorUI-uniapp#12]
`<view class="container">
		<tui-swipe-action :actions="actions"  @click="handlerButton" v-for="(item,index) in cartList"
		 :key="index" :params="item">
			<template v-slot:content>
				<view class="list-item">
					
					<view class="item-box">
						<view class="item-title">{{item.title}}</view>
						<view class="item-time">2019-06-01</view>
					</view>
				</view>
			</template>
		</tui-swipe-action>
	</view>`

import tuiSwipeAction from '@/components/swipe-action/swipe-action.vue';

actions: [{
					name: '删除',
					color: '#fff',
					fontsize: 30,//单位upx
					width: 80, //单位px
					//icon: 'like.png',//此处为图片地址
					background: '#ed3f14'
				},
			]
使用方式都是按照demo的使用方式来使用的,但是我的在显示时出现了乱码的情况,这个是什么问题呢？
“删除”变成了这个“ɾ��”

**Comment by dingyong0214** [comment]
看一下例子有没有问题------------------ 原始邮件 ------------------
发件人: "Give-me-sweets"<notifications@github.com>
发送时间: 2019年11月11日(星期一) 晚上6:40
收件人: "dingyong0214/ThorUI-uniapp"<ThorUI-uniapp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [dingyong0214/ThorUI-uniapp] 使用swipe-action乱码问题 (#12)



<view class="container"> <tui-swipe-action :actions="actions"  @click="handlerButton" v-for="(item,index) in cartList" :key="index" :params="item"> <template v-slot:content> <view class="list-item">  <view class="item-box"> <view class="item-title">{{item.title}}</view> <view class="item-time">2019-06-01</view> </view> </view> </template> </tui-swipe-action> </view>
 import tuiSwipeAction from '@/components/swipe-action/swipe-action.vue';
 actions: [{ name: '删除', color: '#fff', fontsize: 30,//单位upx width: 80, //单位px //icon: 'like.png',//此处为图片地址 background: '#ed3f14' }, ]
 使用方式都是按照demo的使用方式来使用的,但是我的在显示时出现了乱码的情况,这个是什么问题呢？
 “删除”变成了这个“&#x27E;  ”
 
&mdash;

**Comment by Give-me-sweets** [comment]
例子没问题的，我的代码粘到例子上也没有问题，我是按照正常创建uni-app的模板来创建的，但是引入使用就是乱码，想问一下是不是和里面什么东西冲突了

**Comment by Give-me-sweets** [comment]
会不会是pages.json配置会有影响的，我把例子循环的数组粘过来也是乱码的

**Comment by dingyong0214** [comment]
重新建个项目试一下，是不是编码问题------------------ 原始邮件 ------------------
发件人: "Give-me-sweets"<notifications@github.com>
发送时间: 2019年11月12日(星期二) 上午9:44
收件人: "dingyong0214/ThorUI-uniapp"<ThorUI-uniapp@noreply.github.com>;
抄送: "echo."<1062884167@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [dingyong0214/ThorUI-uniapp] 使用swipe-action乱码问题 (#12)



会不会是pages.json配置会有影响的，我把例子循环的数组粘过来也是乱码的
 
&mdash;

**Comment by Give-me-sweets** [comment]
应该是编码问题，重建一个默认uni-app模板是没问题的
