### ISSUE TITLE
vue3推荐使用依赖注入，而不是绑定全局变量

### ISSUE THREAD

**Issue by cvpv** [dingyong0214/ThorUI-uniapp#120]
我看到在示例demo中使用绑定全局属性来使得子组件this获取相关功能

```javascript
// #ifdef VUE3
import {
	createSSRApp
} from 'vue'
export function createApp() {
	const app = createSSRApp(App)
	app.use(store)
	app.config.globalProperties.tui = tui;
	return {
		app
	}
}
// #endif
```

这在组合式api的调用中，必须使用内部方法getCurrentInstance 获取，具有风险
`Because the instance is an internal instance that exposes non-public APIs. Anything you use from that instance can technically break between any release types, since they are not subject to semver constraints.`

建议改为依赖注入写法
```
  app.provide('tui', tui) // vue3的推荐用法
```

**Comment by dingyong0214** [comment]
已记录
