### ISSUE TITLE
Bug提交

### ISSUE THREAD

**Issue by 18651440358** [dingyong0214/ThorUI-uniapp#121]
#### 1. 默认选择日期配置无效
<img width="434" alt="截屏2024-03-25 16 16 38" src="https://github.com/dingyong0214/ThorUI-uniapp/assets/44701892/cb4e7b1f-d829-4489-a03c-26f08b70dd01">

#### 2. 二次点击选择框出现了Bug
<img width="434" alt="截屏2024-03-25 16 18 37" src="https://github.com/dingyong0214/ThorUI-uniapp/assets/44701892/f2937686-287e-41fb-83d1-a3e2a6808fef">
<img width="434" alt="截屏2024-03-25 16 18 49" src="https://github.com/dingyong0214/ThorUI-uniapp/assets/44701892/af067381-9616-43af-b659-94f219edce58">
<img width="434" alt="截屏2024-03-25 16 19 12" src="https://github.com/dingyong0214/ThorUI-uniapp/assets/44701892/ddebefeb-cc47-4262-8d57-f8b4358a6a5b">

**Comment by dingyong0214** [comment]
已记录，感谢反馈
