### ISSUE TITLE
有计划适配uni-app X吗

### ISSUE THREAD

**Issue by godcop** [dingyong0214/ThorUI-uniapp#122]

**Comment by brotherzhoujie** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dingyong0214** [comment]
目前正在开发组合式api组件（vue3+ts），上线后就会迁移并适配uniapp x。
