### ISSUE TITLE
商品列表Nvue布局问题

### ISSUE THREAD

**Issue by gsoec** [dingyong0214/ThorUI-uniapp#14]
![image](https://user-images.githubusercontent.com/26665579/69096698-c687e680-0a09-11ea-8c23-e554eb6c0639.png)

Hbuilder版本2.4.2
小米Android 8.1.0

**Comment by dingyong0214** [comment]
目前nvue页面编译模式是weex，自己切换一下编译模式，下版本支持uni-app编译模式
