### ISSUE TITLE
全局Style统一问题

### ISSUE THREAD

**Issue by catfishlty** [dingyong0214/ThorUI-uniapp#17]
近两个月来，一直在使用Thor-UI，也非常看好整体的设计，但是在使用过程中仍然遇到很多问题，针对这些问题对组件做了些自定义修改。
其中最严重的问题在于，整体项目如果需要更改主题色彩，则需要到组件中每一个使用该颜色的位置更改RGB16进制码，这样的操作工作量大且很容易出错，因此，我希望能够引入uni-app官方推荐的scss预处理器，在降低代码冗余的同时，可以全局统一管理色彩等元素。
如果需要也可告知，我可以协助参与项目。

**Comment by dingyong0214** [comment]
感谢反馈，后期会考虑统一处理
