### ISSUE TITLE
抽屉滚动问题。  在微信小程序下，真机，内容大于屏幕时，滚动失败。  官方推荐使用 scroll-view

### ISSUE THREAD

**Issue by zhangyq233** [dingyong0214/ThorUI-uniapp#19]
https://github.com/dingyong0214/ThorUI-uniapp/blob/93006dd7d3b9d656ada7acb1fcf4ac3b5df87ee6/components/drawer/drawer.vue#L88

**Comment by dingyong0214** [comment]
去看一下商城模板中，商品列表中的使用
