### ISSUE TITLE
ActionSheet组件显示错位

### ISSUE THREAD

**Issue by yimengshinian** [dingyong0214/ThorUI-uniapp#2]
iphonex --真机显示效果如下图
![微信图片_20190709095500](https://user-images.githubusercontent.com/46439489/60853703-da3b6900-a22f-11e9-891a-38b1832f5d94.jpg)

----------------------------------------------  分割线  -------------------------------------------------

![微信图片_20190709095512](https://user-images.githubusercontent.com/46439489/60853704-dad3ff80-a22f-11e9-80ac-7f163bc051b3.jpg)

----------------------------------------------  分割线  -------------------------------------------------

![微信图片_20190709095517](https://user-images.githubusercontent.com/46439489/60853705-db6c9600-a22f-11e9-9f85-6ca33eb88da3.jpg)

**Comment by dingyong0214** [comment]
感谢反馈，该问题已修复
