### ISSUE TITLE
modal组件内嵌textarea的时候，modal关闭时，placeholder的字会显示，请看图

### ISSUE THREAD

**Issue by zhangyq233** [dingyong0214/ThorUI-uniapp#23]
![image](https://user-images.githubusercontent.com/28673757/72028942-56863600-32bf-11ea-85de-23f1d3d7a316.png)
![image](https://user-images.githubusercontent.com/28673757/72029020-89c8c500-32bf-11ea-9bfe-849a02bf0e4d.png)
![image](https://user-images.githubusercontent.com/28673757/72029035-92b99680-32bf-11ea-9aa2-2b9117196734.png)
![image](https://user-images.githubusercontent.com/28673757/72029042-9a793b00-32bf-11ea-8aed-b400b9ec6a24.png)

**Comment by zhangyq233** [comment]
<tui-modal :show="modal9" @cancel="hide9" :custom="true" :fadein="true">
			<view class="tui-modal-custom">
				<view class="tui-prompt-title">邮箱</view>
				
				<textarea v-model="email" :maxlength="20" placeholder="填写您的需求" />
				<tui-button shape="circle" @click="handleClick9" size="small">立即提交</tui-button>
			</view>
		</tui-modal>

**Comment by dingyong0214** [comment]
手动控制一下textarea的显示隐藏，条件和modal的条件一致，这个应该是官方的bug
