### ISSUE TITLE
tuiNomore 组件visible动态修改问题

### ISSUE THREAD

**Issue by Tonyvog** [dingyong0214/ThorUI-uniapp#25]
![image](https://user-images.githubusercontent.com/59596100/75206782-2da7fa80-57b2-11ea-8d7f-03ae42d72456.png)
如图第一种方式生效，第二种方式当方式只在第一次修改的时候生效后续无法生效

**Comment by dingyong0214** [comment]
换种写法，这个只能说明你的值没更新到
