### ISSUE TITLE
吸顶组件怎么才能优化以下，兼容安卓

### ISSUE THREAD

**Issue by Kole6** [dingyong0214/ThorUI-uniapp#28]
吸顶组件怎么才能优化以下，兼容安卓

**Comment by dingyong0214** [comment]
描述清楚一点，扫码下载案例 android app看一下，或者哪些android不支持

**Comment by Kole6** [comment]
V3模式编译的情况下，吸顶不起作用

**Comment by dingyong0214** [comment]
1.4.3已经修复此问题，尚未发布新版本，如果需要加交流群@我 给你发新组件
