### ISSUE TITLE
项目还在维护吗？

### ISSUE THREAD

**Issue by jerryliu306** [dingyong0214/ThorUI-uniapp#32]

**Comment by dingyong0214** [comment]
维护，项目在做v3编译兼容调整

**Comment by dingyong0214** [comment]
下个版本更新如下：


1.新增日历组件  

2.新增裁剪图片功能

3.地图支持H5

4.表单验证优化:非必填情况下,如果值为空,则不进行校验，不为空则进行校验

5.发布H5、QQ小程序以及Android App。H5地址：https://www.thorui.cn/h5/#/ ，QQ小程序搜索ThorUI,apk前往https://www.thorui.cn/下载

6.针对支付宝小程序做了部分优化调整。

7.nvue支持uni-app编译模式

8.新增自定义tabbar使用模板，小程序参考：https://github.com/dingyong0214/AfterSale，uni-app参考：https://github.com/dingyong0214/tabbar-uniapp


9.引入优化uParse

10.搜索页面新增关键词高亮显示

11.新增navbar上拉加载下拉刷新案例

12.吸顶组件数据动态加载案例

13.v3编译

14.支持easycom组件模式，直接在页面中使用组件，无需引入注册

15.头像、图片组合组件

16.NavationBar导航组件

17.圆形进度条组件

**Comment by fallowu** [comment]
> 维护，项目在做v3编译兼容调整

v3编译是什么版本号？
