### ISSUE TITLE
app端扩展组件tabBar中间按钮凸起样式有问题

### ISSUE THREAD

**Issue by ceuer** [dingyong0214/ThorUI-uniapp#34]
app端扩展组件tabBar中间按钮凸起样式有问题：蓝色图片不在凸起的半圆中间位置

另外就是直接导入组件库运行报错。
nvue中不支持如下css。如全局或公共样式受影响，建议将告警样式写在ifndef APP-PLUS-NVUE的条件编译中，详情如下：
23:39:23.574 ERROR: Selector `page` is not supported. Weex only support single-classname selector at App.vue:18
23:39:23.586 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:19
23:39:23.586 WARNING: `display` is not a standard property name (may not be supported) at App.vue:23
23:39:23.596 WARNING: `box-sizing` is not a standard property name (may not be supported) at App.vue:25
23:39:23.596 ERROR: Selector `button::after` is not supported. Weex only support single-classname selector at App.vue:31
23:39:23.606 WARNING: `border` is not a standard property name (may not be supported) at App.vue:32
23:39:23.621 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:38
23:39:23.630 WARNING: `white-space` is not a standard property name (may not be supported) at App.vue:42
23:39:23.643 WARNING: `content` is not a standard property name (may not be supported) at App.vue:50
23:39:23.643 WARNING: `border-bottom` is not a standard property name (may not be supported) at App.vue:52
23:39:23.661 WARNING: `-webkit-transform` is not a standard property name (may not be supported) at App.vue:53
23:39:23.677 WARNING: `border-bottom` is not a standard property name (may not be supported) at App.vue:60
23:39:23.678 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:67
23:39:23.698 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:74
23:39:23.698 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:77
23:39:23.710 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:81
23:39:23.710 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:85
23:39:23.721 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:89
23:39:23.722 WARNING: `background` is not a standard property name (may not be supported), suggest `background-color` at App.vue:94

**Comment by dingyong0214** [comment]
已解决，等待版本发布
