### ISSUE TITLE
uniapp运行时报错

### ISSUE THREAD

**Issue by qhl100** [dingyong0214/ThorUI-uniapp#38]
项目 'ThorUI组件库' 开始编译...
17:26:38.174 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
17:26:38.188 正在编译中...
17:26:39.323  INFO  Starting development server...
17:27:16.034 WARNING: Module Warning (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/templateLoader.js):
17:27:16.046 (Emitted value instead of an instance of Error) <v-uni-view v-for="item in regionArr">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
17:27:16.047 Module Warning (from ./node_modules/postcss-loader/src/index.js):
17:27:16.057 Warning
17:27:16.057 (393:2) Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
17:27:16.064 Module Warning (from ./node_modules/postcss-loader/src/index.js):
17:27:16.074 Warning
17:27:16.074 (393:2) Second Autoprefixer control comment was ignored. Autoprefixer applies control comment to whole block, not to next rules.
17:27:16.080 Module Warning (from ./node_modules/postcss-loader/src/index.js):
17:27:16.081 Warning
17:27:16.086 (394:2) Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
17:27:16.087 Module Warning (from ./node_modules/postcss-loader/src/index.js):
17:27:16.093 Warning
17:27:16.094 (399:2) Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
17:27:16.100 Module Warning (from ./node_modules/postcss-loader/src/index.js):
17:27:16.101 Warning
17:27:16.106 (402:2) Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
17:27:16.107 Module Warning (from ./node_modules/postcss-loader/src/index.js):
17:27:16.112 Warning
17:27:16.116 (415:2) Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
17:27:16.121   App running at:
17:27:16.126   - Local:   http://localhost:8080/ 
17:27:16.127   - Network: http://192.168.31.100:8080/

**Comment by dingyong0214** [comment]
你这连人家开发工具还没整明白
