### ISSUE TITLE
扩展组件 级联选择点击了第一级菜单后，在控制台报了一个错误

### ISSUE THREAD

**Issue by tyonly** [dingyong0214/ThorUI-uniapp#44]
演示地址 ：[https://www.thorui.cn/h5/#/pages/extend/selection/selection](url) ，
点击 第一级菜单 ：高一(二)班，控制台报错 TypeError: t.changedTouches[0] is undefined

**Comment by dingyong0214** [comment]
没有重现，说一下你的运行环境

**Comment by tyonly** [comment]
PC 版firefox下面运行。模拟手机IPHONE 6/7/8

**Comment by dingyong0214** [comment]
或略firefox
