### ISSUE TITLE
在 tui-drawer 里面使用uni.showLoading ，showloading 提示框显示不出来

### ISSUE THREAD

**Issue by tyonly** [dingyong0214/ThorUI-uniapp#45]
在tui-drawer  里面放上一个按钮，点击 该按钮，期望提示：正在加载中。。。，结果页面上是空的，没有提示

**Comment by tyonly** [comment]
同样tui.toast也不会显示。关闭 tui-drawer 可以正常显示

**Comment by dingyong0214** [comment]
h5中将showLoading层级设高一点，或者自己写一个loadding

**Comment by tyonly** [comment]
> 
> 
> h5中将showLoading层级设高一点，或者自己写一个loadding

z-inde 已经设置为 9999999 ，还是没有用

**Comment by dingyong0214** [comment]
看你的样式是否生效了
