### ISSUE TITLE
navbar 顶部选项卡错误严重

### ISSUE THREAD

**Issue by basstk** [dingyong0214/ThorUI-uniapp#49]
/pages/index/navbar/navbar
HBuilderX 2.7.9.20200527 版本,严重错位,
![image](https://user-images.githubusercontent.com/26565065/83495139-dec4dc00-a4e9-11ea-93b9-91b8cb5408c9.png)

**Comment by dingyong0214** [comment]
这是什么平台上，看一下案例是不是好的

**Comment by dingyong0214** [comment]
还有，此代码是nvue文件，不能放在vue里面使用

**Comment by basstk** [comment]
及时雨作者.回复速度好快.
就是用案例自带的,原来是nvue,怪不得

**Comment by dingyong0214** [comment]
自己使用vue的话，css要改一下，主要是flex布局，nvue里面默认flex布局，所以很多默认样式是没有的，编译后才会生成，小程序版本是同步的vue版本调整的

**Comment by basstk** [comment]
好的,知道了,多谢回复!
