### ISSUE TITLE
actionsheet组件bug

### ISSUE THREAD

**Issue by chencn** [dingyong0214/ThorUI-uniapp#5]
actionsheet
报错:Props with type Object/Array must use a factory function to return the default value.
需要修改成：
`
			//菜单按钮数组，自定义文本颜色，红色参考色：#e53a37
			itemList: {
				type: Array,
				default:() => [{
					text: "确定",
					color: "#1a1a1a"
				}]
			},`

**Comment by dingyong0214** [comment]
感谢反馈，此问题已经修复，尚未更新
