### ISSUE TITLE
苹果x的聊天输入有bug，现在解决不了，楼主回复一下下

### ISSUE THREAD

**Issue by baozai6795** [dingyong0214/ThorUI-uniapp#50]
![微信图片_20200604193044](https://user-images.githubusercontent.com/53046357/83751772-fba01180-a699-11ea-8fe2-ceeee6e86259.jpg)

**Comment by baozai6795** [comment]
iPhone x 输入法和输入框被挤开，其他版本没什么问题
created() {
		//键盘高度监听
		this.faceList = emoji.en;
		uni.onKeyboardHeightChange(res => {
			this.keyboardHeight = res.height;
			//去除 完成那一栏高度影响
			setTimeout(() => {
				if (this.showIndex == 1 && this.keyboardHeight != 0) {
					this.replyContainerH = this.keyboardHeight;
					
				}
			}, 100);
		});
	},

this.keyboardHeight = res.height-34刚刚好给iPhonex;但是离开输入法，输入框下不来

**Comment by dingyong0214** [comment]
-34的时候判断是否大于0，res.height-34>0?res.height-34:0

**Comment by baozai6795** [comment]
给了之后输入框下不来，如果你测试成功的话你上传你新的代码，图是源代码的，iPhonex才有这种

**Comment by baozai6795** [comment]
给了之后输入框下不来，如果你测试成功的话你上传你新的代码，图是源代码的，iPhonex才有这种
