### ISSUE TITLE
iphonex聊天输入框被顶出高度

### ISSUE THREAD

**Issue by baozai6795** [dingyong0214/ThorUI-uniapp#51]
![IMG_0029](https://user-images.githubusercontent.com/53046357/83831615-5bd69800-a71a-11ea-8647-dd200641fb18.PNG)

**Comment by dingyong0214** [comment]
等待发版本，不要一直在这刷问题

**Comment by baozai6795** [comment]
什么时候发呐

**Comment by dingyong0214** [comment]
已经更新
