### ISSUE TITLE
tab标签 tui-tabs css样式都是undefined

### ISSUE THREAD

**Issue by Ya-hui** [dingyong0214/ThorUI-uniapp#53]
![image](https://user-images.githubusercontent.com/13138164/83969370-3d32f580-a902-11ea-8b8e-2c46de6544f4.png)
使用方式：
![image](https://user-images.githubusercontent.com/13138164/83969385-5340b600-a902-11ea-98bf-9fe66809ceff.png)

我后面把官网提供的demo 直接拿到我这里运行 样式也都是undefined

**Comment by view0927** [comment]
组件没引入吧，案例中使用的easycom组件模式，如果你项目不是，需要手动引入组件

**Comment by Ya-hui** [comment]
是使用的easycom组件模式 其他模板页面样式都是ok的

**Comment by dingyong0214** [comment]
仔细检查一下，对照参数，看是不是传的不对

**Comment by Ya-hui** [comment]
@dingyong0214 我把案例中的代码直接复制到我的项目中也是样式不对 undefined，easycom组件模式后还需要引入一些其他东西吗？

**Comment by dingyong0214** [comment]
主要看匹配路径对不对，组件不需要引入其他的东西，看一下你的样式是不是哪里影响到了

**Comment by Ya-hui** [comment]
@dingyong0214 其他组件是可以用的 匹配路径应该没啥问题。如果直接把案例中的复制粘贴过来也同样是undefined 
![image](https://user-images.githubusercontent.com/13138164/83970176-d3691a80-a906-11ea-8f90-cf9a82ee0cc5.png)

**Comment by Ya-hui** [comment]
@dingyong0214 @view0927 该问题已解决，我把开发者工具退出 重新打开一下就好了。很坑逼的问题 浪费时间
