### ISSUE TITLE
裁剪组件bug

### ISSUE THREAD

**Issue by fangxingguang** [dingyong0214/ThorUI-uniapp#57]
作者你好：

发现一个问题，
图片裁剪不拖动图片直接点击右下角完成，截取的图片尺寸错误，正方形的，截取结果是长方形的，但是如果拖动一下图片，再点击右下角完成，截取就正常了

PS：git clone的最新代码，微信开发者工具也是最新版

**Comment by dingyong0214** [comment]
此bug已修复，下个版本更新，可以使用非wxs版本

**Comment by ramocky** [comment]
没有修复啊~~今天还是遇到了
