### ISSUE TITLE
icon组件设置size属性 报错显示得到的是字符串类型

### ISSUE THREAD

**Issue by zcjunblog** [dingyong0214/ThorUI-uniapp#60]
代码:
`<tui-icon name="pic" size=24 color="#49cc90"></tui-icon>`
浏览器报错:
`Invalid prop: type check failed for prop "size". Expected Number with value 24, got String with value "24".`

附图:
![微信截图_20200708174537.png](https://i.loli.net/2020/07/08/z4BGxEsYShUgCK5.png)
![微信截图_20200708174553.png](https://i.loli.net/2020/07/08/w81KEsLOghmMdTJ.png)
![微信截图_20200708174615.png](https://i.loli.net/2020/07/08/QrsPRNMgyBZhK5S.png)

**Comment by dingyong0214** [comment]
size是Number类型，在size前面加冒号，:size="24"

**Comment by zcjunblog** [comment]
> size是Number类型，在size前面加冒号，:size="24"

谢谢大哥
