### ISSUE TITLE
actionsheet 显示异常

### ISSUE THREAD

**Issue by liyuchuan86** [dingyong0214/ThorUI-uniapp#63]
版本：1.5.2
问题：actionsheet 首次页面加载的时候正常，但跳转页面在返回回来打开就只能看到提示了，确定按钮和取消按钮都看不到了
![Screenshot_2020-07-28-21-22-58-13_a2e629f0ea915b4ed11e296a059c9a12](https://user-images.githubusercontent.com/32632734/88671503-f222ab00-d118-11ea-9ff7-97ba2c39b9bd.jpg)

**Comment by dingyong0214** [comment]
测试未发现异常，检查一下是否被其它样式影响，或者提供一个简单demo发送至邮箱1062884167@qq.com
