### ISSUE TITLE
tui-button组件不支持配合form表单的form-type属性

### ISSUE THREAD

**Issue by windylaugit** [dingyong0214/ThorUI-uniapp#64]
tui-button组件不支持配合form表单的form-type属性，导致在form中无法使用tui-button。
而又因为tui-button的样式定义都是scoped，所以使用自定义的button就无法引用tui-button的样式， 这样互相矛盾。
可否在tui-button中增加form-type属性呢？
----------
PS：因是采用npm方式引入thor-ui，故无法自行修改组件的源码。

**Comment by dingyong0214** [comment]
已经支持，注意查看更新

**Comment by windylaugit** [comment]
> 已经支持，注意查看更新

感谢辛苦奉献，  期望尽快同步npm版本至1.5.2
