### ISSUE TITLE
uni-tabs滑块不能居中的bug

### ISSUE THREAD

**Issue by DrRua** [dingyong0214/ThorUI-uniapp#67]
在使用tabs的过程中，我发现，假如有三个项，如果每个项的宽度 itemWidth 不为33.3%，则下方滑块并不能跟每个项对齐。看了一下代码大概知道问题所在，计算滑块左偏移的时候，并没有考虑 itemWidth 不为 winWidth / tabs.length 的情况。这是否是有意为之，望解答。

**Comment by dingyong0214** [comment]
嗯，需要手动传传入itemWidth 的宽度具体值或百分比
