### ISSUE TITLE
建议支持Taro和React

### ISSUE THREAD

**Issue by pincman** [dingyong0214/ThorUI-uniapp#81]
uni-app目前的UI库太多了，Taro没有一个，只有官方的，如果能支持Taro会为广大开发者带来很多的便捷同时也会为作者带来不小的收益，收费也是必须的^v^。而且UNI开源全免费的类似uview的选择到处都是，作者收费部分的模板感觉应该收益不高，再加上uni这种模式本来就是做外包临时性用用的，一般付费率不高。所以作为不懂设计的React开发者强烈建议作者适配一下Taro😄

**Comment by dingyong0214** [comment]
这个在计划之中，后面会支持
