### ISSUE TITLE
很棒的第三方框架库，但是建议对ThorUI框架对uni-app原生框架侵入性进行优化

### ISSUE THREAD

**Issue by yutons** [dingyong0214/ThorUI-uniapp#9]
不可否认，thorUI是一个非常棒的三方框架，但是该框架对uni-app原生框架侵入性太强，建议将thorUI独立打包，转换成可配置的三方框架，减少对原生框架的侵入性，避免后续uni-app框架重要升级涉及到带大量代码变更，同时也方便开发者进行集成

**Comment by dingyong0214** [comment]
等项目完善，会尽快调整
